# Generated by Django 2.0.5 on 2018-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_events_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='description please'),
            preserve_default=False,
        ),
    ]
