var chapters = 
    [
        {
            "city":"Delhi",
            "latitude":"28.6139",
            "longitude":"77.2090",
            "website":"http://girlscript.tech/#01"
        },
        {
            "city":"Mumbai",
            "latitude":"19.0760",
            "longitude":"72.8777",
            "website":"http://girlscript.tech/#02"
        },
        {
            "city":"Bangalore",
            "latitude":"12.9716",
            "longitude":"77.5946",
            "website":"http://girlscript.tech/#03"
        },
        {
            "city":"Allahabad",
            "latitude":"25.4358",
            "longitude":"81.8463",
            "website":"http://girlscript.tech/#04"
        },
        {
            "city":"Ranchi",
            "latitude":"23.3441",
            "longitude":"85.3096",
            "website":"http://girlscript.tech/#05"
        }
    ];