# Generated by Django 2.0.5 on 2018-07-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='featured_image',
            field=models.TextField(default='image link'),
            preserve_default=False,
        ),
    ]
